---

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: True
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY

zones:
  umusicsupplier.com.:
    sources:
      - config
    targets:
      - route53
  uviewapp.com.:
    sources:
      - config
    targets:
      - route53
